citation(package = "base", lib.loc = NULL, auto = NULL)
library(astsa)
library(broom)
library(dplyr)
library(forecast)
library(ggplot2)
library(gridExtra)
library(kableExtra)
library(plyr)
library(reshape2)
library(RMySQL)
library(rlang)
library(tidyr)
library(tidyverse) 
library(tseries)
library(xtable)

packagevec<-list("base","astsa","broom","dplyr","forecast","ggplot2", "gridExtra", "kableExtra",
              "plyr","reshape2","RMySQL","rlang", "tidyr", "tidyverse","tseries","xtable", "XML")
lapply(lapply(packagevec,citation),toBibtex)
